#!/usr/bin/env node
// Generator for src/unicode.ts. Parses scripts/unicode/DerivedCoreProperties.txt
// (Unicode 16.0.0) and emits compact ID_Start / ID_Continue range tables plus
// isIdStart / isIdContinue predicates.
//
// HCL identifier semantics follow UAX #31 with the HCL-specific addition that
// '-' (U+002D HYPHEN-MINUS) is allowed as a continuation character. That rule
// is baked into the generated ID_Continue table so the predicate is a pure
// binary search with no extra conditionals.
//
// To regenerate (e.g. after bumping Unicode): replace
// scripts/unicode/DerivedCoreProperties.txt with the new revision, update the
// UNICODE_VERSION constant below, and run `npm run generate:unicode`.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");

const UNICODE_VERSION = "16.0.0";
const INPUT = join(here, "unicode", "DerivedCoreProperties.txt");
const OUTPUT = join(repoRoot, "src", "unicode.ts");
const HYPHEN_MINUS = 0x002d;

/**
 * Parse one "Derived Property" section (e.g. ID_Start) into a sorted,
 * non-overlapping list of [start, end] ranges (inclusive on both ends).
 */
function parseProperty(text, propertyName) {
  const ranges = [];
  const lineRe = new RegExp(
    "^([0-9A-F]{4,6})(?:\\.\\.([0-9A-F]{4,6}))?\\s*;\\s*" +
      propertyName +
      "\\b",
  );
  for (const rawLine of text.split("\n")) {
    const line = rawLine.replace(/#.*$/, "").trim();
    if (!line) continue;
    const m = lineRe.exec(line);
    if (!m) continue;
    const start = parseInt(m[1], 16);
    const end = m[2] ? parseInt(m[2], 16) : start;
    ranges.push([start, end]);
  }
  ranges.sort((a, b) => a[0] - b[0]);
  return mergeAdjacent(ranges);
}

/** Merge overlapping or directly adjacent ranges. Input must be sorted. */
function mergeAdjacent(ranges) {
  if (ranges.length === 0) return ranges;
  const out = [ranges[0].slice()];
  for (let i = 1; i < ranges.length; i++) {
    const prev = out[out.length - 1];
    const [s, e] = ranges[i];
    if (s <= prev[1] + 1) {
      if (e > prev[1]) prev[1] = e;
    } else {
      out.push([s, e]);
    }
  }
  return out;
}

/** Insert a single code point into a sorted, merged range list. */
function insertCodePoint(ranges, cp) {
  const combined = [...ranges, [cp, cp]].sort((a, b) => a[0] - b[0]);
  return mergeAdjacent(combined);
}

/** Flatten [[s1,e1],[s2,e2]] -> [s1,e1,s2,e2] for Uint32Array storage. */
function flatten(ranges) {
  const out = new Array(ranges.length * 2);
  for (let i = 0; i < ranges.length; i++) {
    out[i * 2] = ranges[i][0];
    out[i * 2 + 1] = ranges[i][1];
  }
  return out;
}

/** Emit a Uint32Array literal broken across lines of `perLine` values. */
function formatTable(flat, perLine = 16) {
  const parts = [];
  for (let i = 0; i < flat.length; i += perLine) {
    parts.push("  " + flat.slice(i, i + perLine).map((n) => "0x" + n.toString(16)).join(", "));
  }
  return parts.join(",\n");
}

const text = readFileSync(INPUT, "utf8");
const idStart = parseProperty(text, "ID_Start");
const idContinueRaw = parseProperty(text, "ID_Continue");

// Bake the HCL hyphen rule into the continue table.
const idContinue = insertCodePoint(idContinueRaw, HYPHEN_MINUS);

const startFlat = flatten(idStart);
const contFlat = flatten(idContinue);

const header = `// AUTO-GENERATED by scripts/generate-unicode.mjs. Do not edit by hand.
// To regenerate: replace scripts/unicode/DerivedCoreProperties.txt with a new
// Unicode revision, update UNICODE_VERSION in the generator, and run
//   npm run generate:unicode
//
// Source: https://www.unicode.org/Public/${UNICODE_VERSION}/ucd/DerivedCoreProperties.txt
// Properties extracted: ID_Start, ID_Continue (UAX #31).
// HCL adds U+002D HYPHEN-MINUS to ID_Continue; that addition is already baked
// into ID_CONTINUE_RANGES, so isIdContinue is a single binary search.
`;

const body = `
/** Unicode version that ID_START_RANGES and ID_CONTINUE_RANGES were derived from. */
export const UNICODE_VERSION = "${UNICODE_VERSION}";

/**
 * Flat [start, end] pairs for code points with the UAX #31 ID_Start property.
 * Ranges are inclusive, sorted ascending by start, and non-overlapping.
 */
export const ID_START_RANGES: Readonly<Uint32Array> = new Uint32Array([
${formatTable(startFlat)},
]);

/**
 * Flat [start, end] pairs for code points with the UAX #31 ID_Continue
 * property, plus U+002D HYPHEN-MINUS to match the HCL2 identifier rule.
 * Ranges are inclusive, sorted ascending by start, and non-overlapping.
 */
export const ID_CONTINUE_RANGES: Readonly<Uint32Array> = new Uint32Array([
${formatTable(contFlat)},
]);

function contains(ranges: Readonly<Uint32Array>, cp: number): boolean {
  // Binary search over logical range indices. Range i occupies
  // ranges[i*2] (start) and ranges[i*2 + 1] (end).
  let lo = 0;
  let hi = (ranges.length >>> 1) - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >>> 1;
    const i = mid << 1;
    const start = ranges[i]!;
    const end = ranges[i + 1]!;
    if (cp < start) hi = mid - 1;
    else if (cp > end) lo = mid + 1;
    else return true;
  }
  return false;
}

/** Returns true if cp may begin an HCL identifier (UAX #31 ID_Start). */
export function isIdStart(cp: number): boolean {
  return contains(ID_START_RANGES, cp);
}

/**
 * Returns true if cp may continue an HCL identifier. Equivalent to UAX #31
 * ID_Continue plus U+002D HYPHEN-MINUS (the HCL-specific extension described
 * in hclsyntax/spec.md).
 */
export function isIdContinue(cp: number): boolean {
  return contains(ID_CONTINUE_RANGES, cp);
}
`;

writeFileSync(OUTPUT, header + body);

const ranges = (flat) => flat.length / 2;
console.log(
  `Wrote ${OUTPUT}\n  Unicode ${UNICODE_VERSION}\n  ID_Start: ${ranges(
    startFlat,
  )} ranges\n  ID_Continue (incl. '-'): ${ranges(contFlat)} ranges`,
);
